# Generated by Django 4.0.1 on 2022-01-22 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '0003_alter_about_options_alter_tech_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Nombre del proyecto')),
                ('description', models.TextField(verbose_name='Descripción del proyecto')),
                ('logo', models.ImageField(upload_to='proyectos/', verbose_name='Logo proyecto')),
                ('url', models.URLField(blank=True, verbose_name='Enlace al proyecto')),
                ('screenshot', models.ImageField(upload_to='pantalla_proyectos/', verbose_name='Captura proyecto')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('technologies', models.ManyToManyField(to='about.Tech', verbose_name='Tecnologías')),
            ],
            options={
                'verbose_name': 'Proyecto',
                'verbose_name_plural': 'Proyectos',
                'ordering': ['name'],
            },
        ),
    ]
