# Generated by Django 4.0.1 on 2022-01-22 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('about', '0003_alter_about_options_alter_tech_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Carreer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job', models.CharField(max_length=150, verbose_name='Puesto')),
                ('company', models.CharField(max_length=150, verbose_name='Compañía')),
                ('logo_company', models.ImageField(upload_to='companies/', verbose_name='Logo de empresa')),
                ('period_start', models.DateField(verbose_name='Fecha inicio')),
                ('period_end', models.DateField(verbose_name='Fecha fin')),
                ('description', models.TextField(verbose_name='Descripción')),
                ('create_date', models.DateTimeField(auto_now_add=True, verbose_name='Fecha de creación')),
                ('update_date', models.DateTimeField(auto_now=True, verbose_name='Fecha de actualización')),
                ('technologies', models.ManyToManyField(to='about.Tech', verbose_name='Tecnologías')),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Puestos de trabajo',
                'ordering': ['-period_end'],
            },
        ),
    ]
