# Generated by Django 4.0.1 on 2022-01-21 12:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='About',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.TextField(verbose_name='Extracto personal')),
                ('name', models.CharField(max_length=200, verbose_name='Nombre y apellidos')),
                ('country', models.CharField(max_length=100, verbose_name='Pais')),
                ('city', models.CharField(max_length=100, verbose_name='Ciudad')),
                ('phone', models.CharField(max_length=200, verbose_name='Teléfono')),
                ('email', models.EmailField(max_length=254, verbose_name='Correo Electrónico')),
                ('github', models.URLField(verbose_name='Github')),
                ('linkedin', models.URLField(verbose_name='LinkedIn')),
            ],
        ),
        migrations.CreateModel(
            name='TechType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Tipo de tecnología')),
            ],
        ),
        migrations.CreateModel(
            name='Tech',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Tecnología')),
                ('logo', models.ImageField(upload_to='tecnologias/', verbose_name='Logo')),
                ('time', models.DateField(verbose_name='Experiencia')),
                ('level', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5')], max_length=100, verbose_name='Nivel')),
                ('profesional_use', models.BooleanField(default=False, verbose_name='Uso profesional')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.techtype', verbose_name='Tipo')),
            ],
        ),
    ]
