# Generated by Django 4.0.1 on 2022-01-21 15:06

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='photo',
            field=models.ImageField(default=django.utils.timezone.now, upload_to='foto/', verbose_name='Fotografía'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='about',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='about',
            name='video',
            field=models.URLField(blank=True, verbose_name='Enlace Video presentación'),
        ),
        migrations.AddField(
            model_name='tech',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='tech',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='techtype',
            name='create_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='techtype',
            name='update_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
