# Generated by Django 4.0.1 on 2022-01-22 10:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_about_create_date_about_photo_about_update_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='about',
            options={'verbose_name': 'Información personal', 'verbose_name_plural': 'Datos personales'},
        ),
        migrations.AlterModelOptions(
            name='tech',
            options={'ordering': ['name'], 'verbose_name': 'Tecnología', 'verbose_name_plural': 'Tecnologías'},
        ),
        migrations.AlterModelOptions(
            name='techtype',
            options={'verbose_name': 'Tipo de tecnología', 'verbose_name_plural': 'Tipos de tecnologías'},
        ),
    ]
