# Generated by Django 4.0.1 on 2022-01-26 10:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_alter_about_options_alter_tech_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='about',
            name='subtitle',
            field=models.CharField(default=0, max_length=250, verbose_name='Puesto'),
            preserve_default=False,
        ),
    ]
